#!/usr/bin/env python3
"""Interactive, non-destructive local MySQL setup. Root credentials are never saved."""
import argparse
import getpass
import json
from pathlib import Path
import re
import secrets
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from lms.config import identifier
from scripts.sql_utils import execute_script


def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--empty",action="store_true",help="Create an empty workspace instead of importing fictional sample records.")
    parser.add_argument("--database",default="lms")
    parser.add_argument("--host",default="127.0.0.1")
    parser.add_argument("--port",type=int,default=3306)
    parser.add_argument("--admin-user",default="root")
    parser.add_argument("--app-user",default="lms_app")
    parser.add_argument("--account-host",default="localhost",help="Host allowed to use the app's MySQL account. Local setup uses localhost and 127.0.0.1.")
    args=parser.parse_args()
    if (ROOT/".env").exists():
        print("A .env file already exists. It has not been changed. Use run.sh, or follow README.md for manual configuration.")
        return 1
    try:
        database,user=identifier(args.database),identifier(args.app_user)
    except ValueError as exc:
        print(exc); return 1
    if user.lower()=="root":
        print("Choose a separate application user, not root."); return 1
    try:
        import mysql.connector
    except ImportError:
        print("Install dependencies first: python -m pip install -r requirements.txt"); return 1
    print("Coursebook / MySQL setup")
    print(f"Server: {args.host}:{args.port} | Database: {database}")
    print("Existing records will not be deleted. Use a fresh database and a new app account.")
    password=getpass.getpass(f"MySQL password for {args.admin_user} (not saved): ")
    connection=None
    try:
        connection=mysql.connector.connect(host=args.host,port=args.port,user=args.admin_user,password=password,connection_timeout=8,autocommit=False)
        with connection.cursor() as cursor:
            cursor.execute("SELECT VERSION()")
            server_version=str(cursor.fetchone()[0])
            match=re.match(r"(\d+)\.(\d+)\.(\d+)",server_version)
            if "mariadb" in server_version.lower() or not match or tuple(map(int,match.groups()))<(8,0,16):
                raise RuntimeError("This project requires Oracle MySQL 8.0.16 or newer. MySQL 8.4 is the recommended target.")
            cursor.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %s",(database,))
            if cursor.fetchone()[0]:
                raise RuntimeError("That database already contains tables. Use --database with a new name, or configure the existing database manually.")
            hosts=[args.account_host]
            if args.account_host=="localhost" and args.host in {"127.0.0.1","localhost"}:
                hosts.append("127.0.0.1")
            for host in hosts:
                cursor.execute("SELECT COUNT(*) FROM mysql.user WHERE User=%s AND Host=%s",(user,host))
                if cursor.fetchone()[0]:
                    raise RuntimeError(f"The account {user}@{host} already exists. Choose a new --app-user; existing account passwords are never overwritten.")
            cursor.execute(f"CREATE DATABASE IF NOT EXISTS `{database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
        connection.database=database
        execute_script(connection,ROOT/"database/schema.sql")
        if not args.empty:
            execute_script(connection,ROOT/"database/sample_data.sql")
        app_password=secrets.token_urlsafe(32)
        with connection.cursor() as cursor:
            for host in hosts:
                cursor.execute("CREATE USER %s@%s IDENTIFIED BY %s",(user,host,app_password))
                cursor.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON `{database}`.* TO %s@%s",(user,host))
        connection.commit()
        values={"DB_HOST":args.host,"DB_PORT":str(args.port),"DB_NAME":database,"DB_USER":user,"DB_PASSWORD":app_password,"DB_SSL_CA":"","INSTITUTE_NAME":"Learning & Training Institute","APP_CURRENCY":"PKR","APP_DATA_MODE":"live" if args.empty else "sample","PRIVACY_CONTACT":""}
        config="# Generated by scripts/setup.py. Keep this file private.\n"+"\n".join(f"{key}={json.dumps(value)}" for key,value in values.items())+"\n"
        target=ROOT/".env"
        target.write_text(config,encoding="utf-8")
        target.chmod(0o600)
        print("Setup complete. Created five related tables and a restricted app account.")
        print("Imported fictional sample records." if not args.empty else "The workspace is empty and ready for your records.")
        print("Next: python scripts/doctor.py")
        print("Then: python -m streamlit run app.py")
        return 0
    except (mysql.connector.Error,RuntimeError,OSError) as exc:
        if connection:
            connection.rollback()
        print(f"Setup stopped: {exc}")
        print("No existing records were intentionally removed. MySQL DDL may already have created tables or accounts; inspect them before retrying.")
        return 1
    finally:
        if connection:
            connection.close()


if __name__=="__main__":
    raise SystemExit(main())
